loan_analytics:

  target: dev

  outputs:

    dev:

      type: postgres

      host: localhost

      user: postgres

      password: your_password

      port: 5432

      dbname: loan_analytics

      schema: public

      threads: 4